---
title: "Tidy data reshaping & summaries"
subtitle: "demonstration"
author: "Athanasia Monika Mowinckel"
output:
  xaringan::moon_reader:
    css: [lcbc-uio.css, lcbc-uio-fonts.css, default]
    lib_dir: libs
    nature:
      titleSlideClass: [middle, right]
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false 
      ratio: "16:9"
---
layout: true
    
<div class="my-sidebar"></div> 

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      error = FALSE, 
                      warning = FALSE)

# These are the defaults
xaringanExtra::use_extra_styles(
  hover_code_line = TRUE,         #<<
  mute_unhighlighted_code = TRUE  #<<
)

library(knitr)
library(tidyquintro)
```

class: inverse, middle, center
name: pivots

# pivots

---

```{r}
penguins |> 
  pivot_longer(contains("_")) 
```

---

```{r}
penguins |> 
  pivot_longer(contains("_"), # select the columns
               names_to = c("body_part", "measure", "unit"), # break them into these columns
               names_sep = "_") # break the column names on this character
```

---

```{r}
penguins |> 
  pivot_longer(contains("_"),
               names_to = c("body_part", 
                            "measure", 
                            "unit"),
               names_sep = "_") |> 
  
  ggplot(aes(x = value, fill = species)) + 
  geom_density() + 
  facet_wrap(~ body_part, scales = "free") +
  scale_fill_viridis_d(alpha = .5) +
  theme(legend.position = "bottom")
```


---

```{r}
penguins_long <- penguins |> 
  pivot_longer(contains("_"),
               names_to = c("body_part", 
                            "measure", 
                            "unit"),
               names_sep = "_") 

penguins_long |> 
  pivot_wider(names_from = c("body_part", "measure", "unit"), # pivot these columns
              values_from = "value", # take the values from here
              names_sep = "_") # separate names_from with this character
```

---
class: inverse, middle, center
name: summaries

# summaries

---

```{r}
penguins |> 
  summarise(mean(bill_length_mm, na.rm = TRUE))
```


---

```{r}
penguins |> 
  group_by(species) |> 
  summarise(m_bill_length = mean(bill_length_mm, na.rm = TRUE))
```


---

```{r}
penguins |> 
  group_by(species, island) |> 
  summarise(m_bill_length = mean(bill_length_mm, na.rm = TRUE))
```

---

```{r}
penguins |> 
  group_by(species, island) |> 
  summarise(across(bill_length_mm,
                   mean
  ))
```

---

```{r}
penguins |> 
  group_by(species, island) |> 
  summarise(across(bill_length_mm,
                   list(mean, sd)
  ))
```

---

```{r}
penguins |> 
  group_by(species, island) |> 
  summarise(across(bill_length_mm,
                   list(mean = mean, sd = sd)
  ))
```

---

```{r}
penguins |> 
  group_by(species, island) |> 
  summarise(across(bill_length_mm,
                   list(mean = mean, sd = sd),
                   .names = "{.fn}"
  ))
```

---

```{r}
penguins |> 
  group_by(species, island) |> 
  summarise(across(contains("_"), 
                   list(Mean = mean, 
                        SD = sd,
                        Min = min,
                        Max = max), 
                   na.rm = TRUE))
```

---

```{r}
penguins |> 
  group_by(species, island) |> 
  summarise(across(contains("_"), 
                   list(Mean = mean, 
                        SD = sd,
                        Min = min,
                        Max = max), 
                   na.rm = TRUE,
                   .names = "{.fn}_{.col}"))
```


---

```{r}
penguins |> 
  group_by(species, island) |> 
  summarise(across(contains("_"), 
                   list(Mean = mean, 
                        SD = sd,
                        Min = min,
                        Max = max), 
                   na.rm = TRUE)) |> 
  pivot_longer(contains("_"),
               names_to = c("body_part", "measure", "unit", "stat"),
               names_sep = "_") |> 
  pivot_wider(names_from = stat, values_from = value)
```

---

```{r}
penguins |> 
  # pivot all the columns we want to summarise
  pivot_longer(contains("_"),
               names_to = c("body_part", "measure", "unit", "stat"),
               names_sep = "_",
               values_drop_na = TRUE) |> 
  # Group by wanted grouping variables, including names of columns we made above
  group_by(species, island, body_part, measure, unit) |> 
  # Summarise and give columns just function name
  summarise(across(value, 
                   list(Mean = mean, 
                        SD = sd,
                        Min = min,
                        Max = max),
                   .names = "{.fn}"))
```

---
class: inverse, middle, center
name: nested

# nested data

---

```{r}
penguins |> 
    nest_by(species, island)
```


---

```{r}
penguins |> 
    nest_by(species, island) |> 
    mutate(lm_model = list(
      lm(bill_length_mm ~ bill_depth_mm, data = data)
      ))
```

---

```{r}
model_penguins <- penguins |> 
  nest_by(species, island) |> 
  mutate(
    lm_model = list(
      lm(bill_length_mm ~ bill_depth_mm, data = data)
    ),
    table = list(broom::tidy(lm_model))
    )
model_penguins
```

---

```{r}
model_penguins |> 
  unnest(data)
```

---

```{r}
model_penguins |> 
  unnest(table) |> 
  select(-lm_model, -data)
```
