---
title: "Tidyquintro course website"
description: |
  A 4 hour workshop with quick introduction to [tidyverse](https://www.tidyverse.org/).
site: distill::distill_website
author:
  - name: Athanasia Monika Mowinckel
    affiliation: "<a href='https://www.oslobrains.no'>Center for Lifespan Changes in Brain and Cognition</a>, University of Oslo, Norway"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```

## Timeline
All parts (except first intro) come with small exercises and breaks between.

- **Introduction to [tidyverse](https://www.tidyverse.org/) concepts** (15 minutes)  

- **Tidy data wrangling** - with translations to base-R (~ 2 hours) 
  - plotting data with [ggplot2](https://ggplot2.tidyverse.org/) (~25 min) 
  - sub-setting data with [dplyr](https://dplyr.tidyverse.org/) (~25 min)  
  - chaining commands with the pipe `|>` (~10 min)  
  - adding and altering variables with [dplyr](https://dplyr.tidyverse.org/)  (~25 min)  

- **Lunch break** (30 min)  

- **Tidy data reshaping & summaries** - avoiding loops (~ 1.5 hours)   
  - pivoting data with [tidyr](https://tidyr.tidyverse.org/) (~25 min) 
  - grouped summaries with [dplyr](https://dplyr.tidyverse.org/) (~25 min)  
  - working with nested data using [purrr](https://purrr.tidyverse.org/) (~25 min) 
  

## Who is this course intended for?

Amy is a third year psychology student preparing to work on her Bachelor's thesis.
At university she was taught to use a point and click analysis software (SPSS), but was recommended by her supervisor to learn R to create a more transparent and flexible way of working.
She needs to use R in managing and analysing the data for her Bachelor's thesis, and has never worked with actual data (as opposed to curated class data for teaching purposes).
Amy feels a little intimidated by the command-line and scripting nature of R, but is eager to learn something new.
She hopes that the skills she learns will also make her a more attractive job applicant once her studies are over. 
Amy benefits from a teaching style that is hands-on and descriptive, with ample opportunity to ask for clarifications interactively.
